# **Import Libraries**

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
print("Libraries Loaded✅")

Libraries Loaded✅

# **EDA**

## **Load The Data**

In [9]:
df_sales = pd.read_csv('C:\\Users\\abhay\\OneDrive\\Desktop\\Data-Analytics-Portfolio\\04_End-To-End-Project\\Chocolate sales\\Data\\sales.csv')
df_stores = pd.read_csv('C:\\Users\\abhay\\OneDrive\\Desktop\\Data-Analytics-Portfolio\\04_End-To-End-Project\\Chocolate sales\\Data\\stores.csv')
df_product = pd.read_csv('C:\\Users\\abhay\\OneDrive\\Desktop\\Data-Analytics-Portfolio\\04_End-To-End-Project\\Chocolate sales\\Data\\products.csv')
df_customer = pd.read_csv('C:\\Users\\abhay\\OneDrive\\Desktop\\Data-Analytics-Portfolio\\04_End-To-End-Project\\Chocolate sales\\Data\\customers.csv')
df_calendar = pd.read_csv('C:\\Users\\abhay\\OneDrive\\Desktop\\Data-Analytics-Portfolio\\04_End-To-End-Project\\Chocolate sales\\Data\\calendar.csv')
print('Data Loaded Boss')

Data Loaded Boss

## **Data Exploration**

### Sales Data

In [11]:
df_sales.head(10)

,order_id,order_date,product_id,store_id,customer_id,quantity,unit_price,discount,revenue,cost,profit
0,0RD00000001,2023-01-07,P0080,S093,C040749,5,14.43,0.15,61.33,42.77,18.56
1,0RD00000002,2023-10-22,P0173,S065,C020161,3,12.01,0.00,36.03,19.06,16.97
2,0RD00000003,2023-05-07,P0115,S078,C048069,2,10.02,0.00,20.04,10.29,9.75
3,0RD00000004,2024-06-23,P0186,S088,C047901,2,14.66,0.10,26.39,16.35,10.04
4,0RD00000005,2024-09-24,P0197,S054,C033950,1,12.34,0.00,12.34,7.94,4.40
5,0RD00000006,2024-03-29,P0160,S089,C008918,4,13.52,0.00,54.08,36.59,17.49
6,0RD00000007,2023-02-26,P0062,S024,C002897,1,11.97,0.10,10.77,7.16,3.61
7,0RD00000008,2023-11-03,P0111,S085,C038072,5,4.62,0.00,23.10,16.15,6.95
8,0RD00000009,2024-10-11,P0135,S029,C003786,4,7.88,0.00,31.52,19.90,11.62
9,0RD00000010,2023-12-17,P0069,S056,C043148,3,8.88,0.00,26.64,18.19,8.45

In [12]:
df_sales.tail(10)

,order_id,order_date,product_id,store_id,customer_id,quantity,unit_price,discount,revenue,cost,profit
999990,0RD00999991,2024-12-07,P0176,S081,C011234,5,8.12,0.0,40.60,27.12,13.48
999991,0RD00999992,2023-01-10,P0034,S019,C012109,1,6.42,0.0,6.42,3.59,2.83
999992,0RD00999993,2023-10-21,P0046,S014,C035070,3,7.26,0.0,21.78,12.72,9.06
999993,0RD00999994,2024-04-30,P0173,S019,C044193,4,10.53,0.0,42.12,28.34,13.78
999994,0RD00999995,2024-07-28,P0127,S055,C007369,1,8.96,0.2,7.17,4.73,2.44
999995,0RD00999996,2023-04-15,P0103,S053,C044763,4,7.45,0.0,29.80,17.27,12.53
999996,0RD00999997,2023-05-26,P0094,S058,C004441,2,6.09,0.0,12.18,7.81,4.37
999997,0RD00999998,2023-07-05,P0097,S041,C044879,3,6.09,0.0,18.27,10.11,8.16
999998,0RD00999999,2024-01-03,P0090,S083,C042525,1,4.90,0.0,4.90,2.56,2.34
999999,0RD01000000,2024-04-10,P0175,S090,C025078,1,7.35,0.1,6.62,3.33,3.28

In [23]:
max_len = max(len(col) for col in df_sales.columns)

print(f"{'Column':<{max_len}} | NaN Count")
print("-" * (max_len + 15))

for col in df_sales.columns:
    print(f"{col:<{max_len}} | {df_sales[col].isna().sum()}")

Column      | NaN Count
--------------------------
order_id    | 0
order_date  | 0
product_id  | 0
store_id    | 0
customer_id | 0
quantity    | 0
unit_price  | 0
discount    | 0
revenue     | 0
cost        | 0
profit      | 0

In [24]:
print(f"Duplicates in the Data is {df_sales.duplicated().sum()}")

Duplicates in the Data is 0

In [25]:
df_sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 11 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   order_id     1000000 non-null  str
 1   order_date   1000000 non-null  str
 2   product_id   1000000 non-null  str
 3   store_id     1000000 non-null  str
 4   customer_id  1000000 non-null  str
 5   quantity     1000000 non-null  int64
 6   unit_price   1000000 non-null  float64
 7   discount     1000000 non-null  float64
 8   revenue      1000000 non-null  float64
 9   cost         1000000 non-null  float64
 10  profit       1000000 non-null  float64
dtypes: float64(5), int64(1), str(5)
memory usage: 83.9 MB

In [26]:
df_sales.describe()

,quantity,unit_price,discount,revenue,cost,profit
count,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000
mean,2.999589,9.002449,0.056248,25.486129,15.291554,10.194565
std,1.413621,3.462902,0.076809,16.367864,9.972706,6.778760
min,1.000000,3.000000,0.000000,2.400000,1.200000,0.730000
25%,2.000000,6.000000,0.000000,12.160000,7.240000,4.780000
50%,3.000000,9.010000,0.000000,21.920000,13.030000,8.600000
75%,4.000000,12.000000,0.150000,35.880000,21.410000,14.170000
max,5.000000,15.000000,0.200000,75.000000,52.430000,37.430000