# **Imports Libraries**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
print("Libraries Loaded")

Libraries Loaded

# **Data Exploration**

## *Load The Data*

In [2]:
anime = input("Enter the Anime file path: ")
rating = input("Enter the Rating file path: ")

df_anime = pd.read_csv(anime)
df_rating = pd.read_csv(rating)

print("Data Loaded Boss✅")

Data Loaded Boss✅

## **Exploration**

### *Rating Data*

In [20]:
df_rating.shape

(7813737, 3)

In [6]:
df_rating.head(10)

   user_id  anime_id  rating
0        1        20      -1
1        1        24      -1
2        1        79      -1
3        1       226      -1
4        1       241      -1
5        1       355      -1
6        1       356      -1
7        1       442      -1
8        1       487      -1
9        1       846      -1

In [8]:
df_rating.tail(10)

         user_id  anime_id  rating
7813727    73515     13161       8
7813728    73515     13331       9
7813729    73515     13599       7
7813730    73515     13659       8
7813731    73515     14345       7
7813732    73515     16512       7
7813733    73515     17187       9
7813734    73515     22145      10
7813735    73516       790       9
7813736    73516      8074       9

In [9]:
df_rating.isna().sum()

user_id     0
anime_id    0
rating      0
dtype: int64

In [11]:
df_rating.duplicated().sum()

np.int64(1)

In [12]:
df_rating.info()

<class 'pandas.DataFrame'>
RangeIndex: 7813737 entries, 0 to 7813736
Data columns (total 3 columns):
 #   Column    Dtype
---  ------    -----
 0   user_id   int64
 1   anime_id  int64
 2   rating    int64
dtypes: int64(3)
memory usage: 178.8 MB

### *Anime Data*

In [19]:
df_anime.shape

(12294, 7)

In [17]:
df_anime.head(10)

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266
5,32935,Haikyuu!!: Karasuno Koukou VS Shiratorizawa Ga...,"Comedy, Drama, School, Shounen, Sports",TV,10,9.15,93351
6,11061,Hunter x Hunter (2011),"Action, Adventure, Shounen, Super Power",TV,148,9.13,425855
7,820,Ginga Eiyuu Densetsu,"Drama, Military, Sci-Fi, Space",OVA,110,9.11,80679
8,15335,Gintama Movie: Kanketsu-hen - Yorozuya yo Eien...,"Action, Comedy, Historical, Parody, Samurai, S...",Movie,1,9.10,72534
9,15417,Gintama&#039;: Enchousen,"Action, Comedy, Historical, Parody, Samurai, S...",TV,13,9.11,81109

In [18]:
df_anime.tail(10)

,anime_id,name,genre,type,episodes,rating,members
12284,26031,Super Erotic Anime,Hentai,OVA,2,4.45,118
12285,34399,Taimanin Asagi 3,"Demons, Hentai, Supernatural",OVA,Unknown,NaN,485
12286,10368,Teleclub no Himitsu,Hentai,OVA,2,4.67,148
12287,9352,Tenshi no Habataki Jun,Hentai,OVA,1,4.33,201
12288,5541,The Satisfaction,Hentai,OVA,1,4.37,166
12289,9316,Toushindai My Lover: Minami tai Mecha-Minami,Hentai,OVA,1,4.15,211
12290,5543,Under World,Hentai,OVA,1,4.28,183
12291,5621,Violence Gekiga David no Hoshi,Hentai,OVA,4,4.88,219
12292,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175
12293,26081,Yasuji no Pornorama: Yacchimae!!,Hentai,Movie,1,5.46,142

In [23]:
df_anime.isna().sum()

anime_id      0
name          0
genre        62
type         25
episodes      0
rating      230
members       0
dtype: int64

In [ ]:
df_anime.duplicated().sum()

np.int64(0)

In [26]:
df_anime.info()

<class 'pandas.DataFrame'>
RangeIndex: 12294 entries, 0 to 12293
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   anime_id  12294 non-null  int64
 1   name      12294 non-null  str
 2   genre     12232 non-null  str
 3   type      12269 non-null  str
 4   episodes  12294 non-null  str
 5   rating    12064 non-null  float64
 6   members   12294 non-null  int64
dtypes: float64(1), int64(2), str(4)
memory usage: 672.5 KB

# **Data Cleaning**

In [45]:
df_anime_copy = df_anime.copy()
df_rating_copy = df_rating.copy()
print("Copy Created Boss✅")

Copy Created Boss✅

In [46]:
df_anime_copy['genre'] = df_anime_copy['genre'].str.split(',')

In [47]:
# DataType Correction
df_anime_copy.loc[df_anime_copy['episodes']=='Unknown','episodes'] = np.nan
df_anime_copy['episodes'] = df_anime_copy['episodes'].astype('float')
df_anime_copy.info()

<class 'pandas.DataFrame'>
RangeIndex: 12294 entries, 0 to 12293
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   anime_id  12294 non-null  int64
 1   name      12294 non-null  str
 2   genre     12232 non-null  object
 3   type      12269 non-null  str
 4   episodes  11954 non-null  float64
 5   rating    12064 non-null  float64
 6   members   12294 non-null  int64
dtypes: float64(2), int64(2), object(1), str(2)
memory usage: 672.5+ KB

In [48]:
# filling NaN values
print('NaN Values Before: ')
print(df_anime_copy.isna().sum())

df_anime_copy['episodes'] = df_anime_copy['episodes'].fillna(round(df_anime_copy['episodes'].median(),0))
df_anime_copy['type'] = df_anime_copy['type'].fillna('Unknown')
df_anime_copy['rating'] = df_anime_copy['rating'].fillna(round(df_anime_copy['rating'].median(),0))
df_anime_copy.explode('genre')
df_anime_copy['genre'] = df_anime_copy['genre'].fillna('Unknown')

print('NaN Values After: ')
df_anime_copy.isna().sum()

NaN Values Before:
anime_id      0
name          0
genre        62
type         25
episodes    340
rating      230
members       0
dtype: int64
NaN Values After:

anime_id    0
name        0
genre       0
type        0
episodes    0
rating      0
members     0
dtype: int64

In [50]:
df_anime_copy.duplicated(subset='anime_id').sum()

np.int64(0)